### ISSUE TITLE
Running latest version of the executable says it is not the latest version

### ISSUE THREAD

**Issue by AnotherUser97** [amakvana/CemuLauncher#1]
**Describe the bug**
As the title says, if I run the latest version on my PC, it will throw an error saying it is not the latest version and will tell me to update it.

**To Reproduce**
1. Download latest version from this repo
2. Place it in the same folder as the Cemu executable
3. Run the launcher, error will be displayed

**Expected behavior**
The application window should load normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/28853742/104796579-6ba07980-57dd-11eb-9572-20a812f73e22.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by amakvana** [comment]
Apologies, this is now sorted in v1.2.0.0. Please confirm, then I can close this.

You may also need to clear your IE cache. Start > Type "Internet Options" > General > Delete > Only check "Temporary Internet Files and website files" > Click "Delete"

**Comment by AnotherUser97** [comment]
Okay thank you it seems to work now

**Comment by amakvana** [comment]
Closed - solved with v1.2.0.0
